language: node_js
node_js:
  - node
script: npm run build
before_deploy:
  - mkdir -p ttrss-reader-${TRAVIS_TAG#v}
  - cp -R public/favicon.png public/index.html public/assets ttrss-reader-${TRAVIS_TAG#v}
  - tar -czf ttrss-reader-${TRAVIS_TAG#v}.tar.gz ttrss-reader-${TRAVIS_TAG#v}
  - rm -fr ttrss-reader-${TRAVIS_TAG#v}
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: '*.tar.gz'
  skip_cleanup: true
  on:
    tags: true
